### ISSUE TITLE
Make the Contributing.md hacktoberfest ready

### ISSUE THREAD

**Issue by olavea** [cloudinary-community/gatsby-transformer-cloudinary#244]
Make the Contributing.md hacktoberfest ready

🔲  Fix internal links to headings
🔲  Clean up language
🔲 We want it to look aaaalmost exactly like this:
[https://github.com/cloudinary-devs/gatsby-source-cloudinary/pull/81](https://github.com/cloudinary-devs/gatsby-source-cloudinary/pull/81)

Remember to:
- Create a new branch and use the issue number when naming your branch: `git checkout -b -<issue number>-<something descriptive>`.
- Commit your changes often: `git commit -a -m <your message>`.

![to-be-or-to-pirate](https://github.com/cloudinary-devs/gatsby-transformer-cloudinary/assets/7642493/fc9aa2a4-3ad3-49fb-bfaf-8a3f29919141)

**Comment by SaarthakMaini** [comment]
I would like to work on this issue.

Please consider assigning the same

**Comment by Abhinavxox** [comment]
@olavea Can you assign this to me? I have checked the other md file that you provided. I will try to update it similarly.

**Comment by olavea** [comment]
Yesss!

Just comment here if you have any questions or ideas.

Best of luck 🥳

Ola


> @olavea Can you assign this to me? I have checked the other md file that you provided. I will try to update it similarly.

**Comment by Abhinavxox** [comment]
Hey @olavea,
I have made the changes you wanted. But should I also add a section on the format to create a new Pull Request, Issue, or the naming convention of the branch like you mentioned:
`git checkout -b -<issue number>-<something descriptive>`

**Comment by olavea** [comment]
👀

**Comment by Abhinavxox** [comment]
> 👀

Is there something wrong?😅

**Comment by raae** [comment]
Pretty sure he means, "I've seen this message and will get back to you"!

**Comment by colbyfayock** [comment]
@olavea should this be closed by https://github.com/cloudinary-devs/gatsby-transformer-cloudinary/pull/247?
